Repository GoGetCustomer/learning-management-system, pull requests merged in 2025-01, with the labels that each got.

#4 merge: main <- feature/extension-modify #3
  .github/PULL_REQUEST_TEMPLATE.md
  lms/src/main/resources/application.properties
  lms/src/main/resources/application.yml
Labels: chore

#10 merge: develop <- feature/add-gitignore #9
  lms/.gitignore
Labels: docs

#11 merge: develop <- feature/auth-security #5
  lms/src/main/java/com/example/lms/domain/instructor/entity/Instructor.java
  lms/src/main/java/com/example/lms/domain/instructor/repository/InstructorRepository.java
  lms/src/main/java/com/example/lms/domain/student/entity/Student.java
  lms/src/main/java/com/example/lms/domain/student/repository/StudentRepository.java
  lms/src/main/java/com/example/lms/domain/user/entity/User.java
  lms/src/main/java/com/example/lms/domain/user/enums/Role.java
  lms/src/test/java/com/example/lms/common/fixture/InstructorFixture.java
  lms/src/test/java/com/example/lms/common/fixture/StudentFixture.java
  lms/src/test/java/com/example/lms/domain/instructor/entity/InstructorTest.java
  lms/src/test/java/com/example/lms/domain/student/entity/StudentTest.java
Labels: feature, test

#13 merge: develop <- feature/change-db-setting-location #12
  .gitignore
  lms/src/main/resources/application.yml
Labels: docs

#15 merge: develop <- feature/course-domain-entity
  lms/build.gradle
  lms/src/main/java/com/example/lms/domain/content/entity/Content.java
  lms/src/main/java/com/example/lms/domain/course/dto/request/CourseCreateRequestDto.java
  lms/src/main/java/com/example/lms/domain/course/dto/request/CourseUpdateRequestDto.java
  lms/src/main/java/com/example/lms/domain/course/dto/response/CourseResponseDto.java
  lms/src/main/java/com/example/lms/domain/course/entity/Course.java
  lms/src/main/java/com/example/lms/domain/course/mapper/CourseMapper.java
  lms/src/main/java/com/example/lms/domain/course/repository/CourseRepository.java
  lms/src/main/java/com/example/lms/domain/course/service/CourseService.java
  lms/src/main/java/com/example/lms/domain/lecture/entity/Lecture.java
  lms/src/test/java/com/example/lms/common/fixture/CourseFixture.java
  lms/src/test/java/com/example/lms/domain/course/mapper/CourseMapperTest.java
  lms/src/test/java/com/example/lms/domain/course/service/CourseServiceTest.java
Labels: feature, test

#16 merge: develop <- feature/ quiz-domain #2
  lms/src/main/java/com/example/lms/domain/answer/entity/Answer.java
  lms/src/main/java/com/example/lms/domain/question/entity/Question.java
  lms/src/main/java/com/example/lms/domain/question/repository/QuestionRepository.java
  lms/src/main/java/com/example/lms/domain/quiz/controller/QuizController.java
  lms/src/main/java/com/example/lms/domain/quiz/dto/QuizRequest.java
  lms/src/main/java/com/example/lms/domain/quiz/dto/QuizResponse.java
  lms/src/main/java/com/example/lms/domain/quiz/entity/Quiz.java
  lms/src/main/java/com/example/lms/domain/quiz/repository/QuizRepository.java
  lms/src/main/java/com/example/lms/domain/quiz/service/QuizService.java
  lms/src/main/resources/application.yml
  lms/src/test/java/com/example/lms/domain/quiz/service/QuizServiceTest.java
Labels: feature, test

#18 merge: develop <- feature/ quiz-domain #2
  lms/src/main/java/com/example/lms/domain/quizGrade/entity/QuizGrade.java
  lms/src/main/java/com/example/lms/domain/quizGrade/repository/QuizGradeRepository.java
  lms/src/test/java/com/example/lms/domain/quizGrade/entity/QuizGradeTest.java
Labels: feature, test

#19 merge: develop <- feature/auth-security #5
  lms/build.gradle
  lms/src/main/java/com/example/lms/common/auth/dto/CustomUserDetails.java
  lms/src/main/java/com/example/lms/common/auth/service/CustomInstructorDetailsService.java
  lms/src/main/java/com/example/lms/common/auth/service/CustomStudentDetailsService.java
  lms/src/main/java/com/example/lms/common/config/RedisConfig.java
  lms/src/main/java/com/example/lms/common/service/RedisService.java
  lms/src/main/java/com/example/lms/domain/instructor/entity/Instructor.java
  lms/src/main/java/com/example/lms/domain/instructor/repository/InstructorRepository.java
  lms/src/main/java/com/example/lms/domain/registration/entity/Registration.java
  lms/src/main/java/com/example/lms/domain/registration/enums/RegistrationStatus.java
  lms/src/main/java/com/example/lms/domain/registration/repository/RegistrationRepository.java
  lms/src/main/java/com/example/lms/domain/student/entity/Student.java
  lms/src/main/java/com/example/lms/domain/student/repository/StudentRepository.java
  lms/src/main/java/com/example/lms/domain/teaching/entity/Teaching.java
  lms/src/main/java/com/example/lms/domain/teaching/repository/TeachingRepository.java
  lms/src/main/resources/application.yml
  lms/src/test/java/com/example/lms/common/auth/service/CustomInstructorDetailsServiceTest.java
  lms/src/test/java/com/example/lms/common/auth/service/CustomStudentDetailsServiceTest.java
  lms/src/test/java/com/example/lms/common/fixture/InstructorFixture.java
  lms/src/test/java/com/example/lms/common/fixture/StudentFixture.java
  lms/src/test/java/com/example/lms/common/service/RedisServiceTest.java
  lms/src/test/java/com/example/lms/domain/instructor/repository/InstructorRepositoryTest.java
  lms/src/test/java/com/example/lms/domain/student/repository/StudentRepositoryTest.java
Labels: feature

#24 merge: develop <- feature/except-swagger-in-security #23
  lms/src/main/java/com/example/lms/common/config/SecurityConfig.java
Labels: chore

#21 merge: develop <- feature/quiz-domain #2
  .gitignore
  lms/src/main/java/com/example/lms/domain/answer/entity/Answer.java
  lms/src/main/java/com/example/lms/domain/answer/repository/AnswerRepository.java
  lms/src/main/java/com/example/lms/domain/question/entity/Question.java
  lms/src/main/java/com/example/lms/domain/quiz/controller/QuizController.java
  lms/src/main/java/com/example/lms/domain/quiz/controller/QuizSubmissionController.java
  lms/src/main/java/com/example/lms/domain/quiz/dto/QuizSubmissionRequest.java
  lms/src/main/java/com/example/lms/domain/quiz/dto/QuizSubmissionResponse.java
  lms/src/main/java/com/example/lms/domain/quiz/entity/Quiz.java
  lms/src/main/java/com/example/lms/domain/quiz/repository/QuizRepository.java
  lms/src/main/java/com/example/lms/domain/quiz/service/QuizService.java
  lms/src/main/java/com/example/lms/domain/quiz/service/QuizSubmissionService.java
  lms/src/main/java/com/example/lms/domain/quizGrade/entity/QuizGrade.java
  lms/src/test/java/com/example/lms/domain/quiz/service/QuizServiceTest.java
  lms/src/test/java/com/example/lms/domain/quiz/service/QuizSubmissionServiceTest.java
Labels: feature, test

#20 merge: develop <- feature/deploy-with-docker #17
  .github/workflows/build-check.yml
  .github/workflows/deploy-ec2.yml
  lms/Dockerfile
Labels: chore

#22 merge: develop <- feature/assignment-domain #7
  lms/src/main/java/com/example/lms/domain/assignment/controller/AssignmentController.java
  lms/src/main/java/com/example/lms/domain/assignment/controller/AssignmentGradeController.java
  lms/src/main/java/com/example/lms/domain/assignment/controller/SubmissionController.java
  lms/src/main/java/com/example/lms/domain/assignment/dto/AssignmentGradeRequest.java
  lms/src/main/java/com/example/lms/domain/assignment/dto/AssignmentGradeResponse.java
  lms/src/main/java/com/example/lms/domain/assignment/dto/AssignmentRequest.java
  lms/src/main/java/com/example/lms/domain/assignment/dto/AssignmentResponse.java
  lms/src/main/java/com/example/lms/domain/assignment/dto/SubmissionRequest.java
  lms/src/main/java/com/example/lms/domain/assignment/dto/SubmissionResponse.java
  lms/src/main/java/com/example/lms/domain/assignment/entity/Assignment.java
  lms/src/main/java/com/example/lms/domain/assignment/entity/AssignmentGrade.java
  lms/src/main/java/com/example/lms/domain/assignment/entity/Submission.java
  lms/src/main/java/com/example/lms/domain/assignment/repository/AssignmentGradeRepository.java
  lms/src/main/java/com/example/lms/domain/assignment/repository/AssignmentRepository.java
  lms/src/main/java/com/example/lms/domain/assignment/repository/SubmissionRepository.java
  lms/src/main/java/com/example/lms/domain/assignment/service/AssignmentGradeService.java
  lms/src/main/java/com/example/lms/domain/assignment/service/AssignmentService.java
  lms/src/main/java/com/example/lms/domain/assignment/service/SubmissionService.java
Labels: feature

#26 merge: develop <- feature/quiz-domain #2
  lms/src/main/java/com/example/lms/domain/quiz/dto/QuizSubmissionRequest.java
  lms/src/main/java/com/example/lms/domain/quiz/dto/QuizSubmissionResponse.java
  lms/src/main/java/com/example/lms/domain/quiz/service/QuizSubmissionService.java
  lms/src/main/java/com/example/lms/domain/quizGrade/entity/QuizGrade.java
  lms/src/test/java/com/example/lms/domain/quizGrade/entity/QuizGradeTest.java
  lms/src/test/java/com/example/lms/domain/quizGrade/service/QuizSubmissionAndGradeTest.java
Labels: feature, test

#25 merge: develop <- feature/auth security #5
  lms/src/main/java/com/example/lms/common/auth/dto/CustomUserDetails.java
  lms/src/main/java/com/example/lms/common/auth/dto/LoginRequestDto.java
  lms/src/main/java/com/example/lms/common/auth/filter/CustomLogoutFilter.java
  lms/src/main/java/com/example/lms/common/auth/filter/CustomUsernamePasswordAuthenticationFilter.java
  lms/src/main/java/com/example/lms/common/auth/filter/InstructorLoginFilter.java
  lms/src/main/java/com/example/lms/common/auth/filter/JwtAuthenticationFilter.java
  lms/src/main/java/com/example/lms/common/auth/filter/StudentLoginFilter.java
  lms/src/main/java/com/example/lms/common/auth/handler/CustomAccessDeniedHandler.java
  lms/src/main/java/com/example/lms/common/auth/handler/CustomAuthenticationEntryPoint.java
  lms/src/main/java/com/example/lms/common/auth/jwt/TokenConstants.java
  lms/src/main/java/com/example/lms/common/auth/jwt/TokenProvider.java
  lms/src/main/java/com/example/lms/common/auth/service/CustomInstructorDetailsService.java
  lms/src/main/java/com/example/lms/common/auth/service/CustomStudentDetailsService.java
  lms/src/main/java/com/example/lms/common/config/SecurityConfig.java
  lms/src/main/java/com/example/lms/common/config/SwaggerConfig.java
  lms/src/main/java/com/example/lms/common/utils/CookieUtil.java
  lms/src/main/java/com/example/lms/common/validation/ValidationGroups.java
  lms/src/main/java/com/example/lms/common/validation/ValidationSequence.java
  lms/src/main/java/com/example/lms/domain/instructor/controller/InstructorController.java
  lms/src/main/java/com/example/lms/domain/instructor/controller/InstructorControllerDocs.java
  lms/src/main/java/com/example/lms/domain/instructor/dto/InstructorCreateRequestDto.java
  lms/src/main/java/com/example/lms/domain/instructor/repository/InstructorRepository.java
  lms/src/main/java/com/example/lms/domain/instructor/service/InstructorService.java
  lms/src/main/java/com/example/lms/domain/student/controller/StudentController.java
  lms/src/main/java/com/example/lms/domain/student/controller/StudentControllerDocs.java
  lms/src/main/java/com/example/lms/domain/student/dto/StudentCreateRequestDto.java
  lms/src/main/java/com/example/lms/domain/student/entity/Student.java
  lms/src/main/java/com/example/lms/domain/student/repository/StudentRepository.java
  lms/src/main/java/com/example/lms/domain/student/service/StudentService.java
  lms/src/main/java/com/example/lms/domain/user/controller/UserController.java
  lms/src/main/java/com/example/lms/domain/user/controller/UserControllerDocs.java
  lms/src/main/java/com/example/lms/domain/user/dto/UserUpdatePasswordRequestDto.java
  lms/src/main/java/com/example/lms/domain/user/entity/User.java
  lms/src/main/java/com/example/lms/domain/user/service/UserService.java
  lms/src/main/resources/application.yml
  lms/src/test/java/com/example/lms/common/auth/jwt/TokenProviderTest.java
  lms/src/test/java/com/example/lms/common/auth/service/CustomInstructorDetailsServiceTest.java
  lms/src/test/java/com/example/lms/common/auth/service/CustomStudentDetailsServiceTest.java
  lms/src/test/java/com/example/lms/common/config/MockCustomUserSecurityContextFactory.java
  lms/src/test/java/com/example/lms/common/config/WithMockCustom.java
  lms/src/test/java/com/example/lms/common/fixture/InstructorFixture.java
  lms/src/test/java/com/example/lms/common/fixture/StudentFixture.java
  lms/src/test/java/com/example/lms/common/reflection/ReflectionFieldSetter.java
  lms/src/test/java/com/example/lms/common/utils/CookieUtilTest.java
  lms/src/test/java/com/example/lms/domain/instructor/entity/InstructorTest.java
  lms/src/test/java/com/example/lms/domain/instructor/repository/InstructorRepositoryTest.java
  lms/src/test/java/com/example/lms/domain/instructor/service/InstructorServiceTest.java
  lms/src/test/java/com/example/lms/domain/student/entity/StudentTest.java
  lms/src/test/java/com/example/lms/domain/student/repository/StudentRepositoryTest.java
  lms/src/test/java/com/example/lms/domain/student/service/StudentServiceTest.java
  lms/src/test/java/com/example/lms/domain/user/controller/UserControllerTest.java
  lms/src/test/java/com/example/lms/domain/user/service/UserServiceTest.java
Labels: feature, test

#30 merge: develop <- feature/add-cd-variable #27
  .github/workflows/deploy-ec2.yml
  lms/Dockerfile
Labels: bug

#29 refactor: Assignment 관련 엔티티에 @Column 어노테이션 추가 #7
  lms/src/main/java/com/example/lms/domain/assignment/entity/Assignment.java
  lms/src/main/java/com/example/lms/domain/assignment/entity/AssignmentGrade.java
  lms/src/main/java/com/example/lms/domain/assignment/entity/Submission.java
Labels: refactor

#36 merge develop <- feature/course-domain
  lms/src/main/java/com/example/lms/LmsApplication.java
  lms/src/main/java/com/example/lms/common/config/JpaAuditingConfig.java
  lms/src/main/java/com/example/lms/common/config/SecurityConfig.java
  lms/src/main/java/com/example/lms/domain/course/controller/CourseController.java
  lms/src/main/java/com/example/lms/domain/course/dto/request/CourseUpdateRequestDto.java
  lms/src/main/java/com/example/lms/domain/course/dto/response/CourseCreateResponseDto.java
  lms/src/main/java/com/example/lms/domain/course/dto/response/CourseResponseDto.java
  lms/src/main/java/com/example/lms/domain/course/mapper/CourseMapper.java
  lms/src/main/java/com/example/lms/domain/course/repository/CourseRepository.java
  lms/src/main/java/com/example/lms/domain/course/service/CourseService.java
  lms/src/main/java/com/example/lms/domain/instructor/dto/InstructorInfo.java
  lms/src/test/java/com/example/lms/common/fixture/CourseFixture.java
  lms/src/test/java/com/example/lms/common/fixture/InstructorFixture.java
  lms/src/test/java/com/example/lms/domain/course/controller/CourseControllerTest.java
  lms/src/test/java/com/example/lms/domain/course/service/CourseServiceTest.java
Labels: feature, test

#38 merge: develop <- feature/quiz-domain #2
  lms/src/main/java/com/example/lms/domain/quiz/dto/QuizRequest.java
  lms/src/main/java/com/example/lms/domain/quiz/dto/QuizSubmissionRequest.java
  lms/src/main/java/com/example/lms/domain/quiz/service/QuizSubmissionService.java
Labels: refactor, question

#39 merge: develop <- feature/instructor-domain #37
  lms/src/main/java/com/example/lms/common/config/SecurityConfig.java
  lms/src/main/java/com/example/lms/domain/instructor/controller/InstructorController.java
  lms/src/main/java/com/example/lms/domain/instructor/controller/InstructorControllerDocs.java
  lms/src/main/java/com/example/lms/domain/instructor/dto/InstructorBasicInfoResponseDto.java
  lms/src/main/java/com/example/lms/domain/instructor/dto/InstructorPersonalInfoResponseDto.java
  lms/src/main/java/com/example/lms/domain/instructor/dto/InstructorUpdateRequestDto.java
  lms/src/main/java/com/example/lms/domain/instructor/entity/Instructor.java
  lms/src/main/java/com/example/lms/domain/instructor/service/InstructorService.java
  lms/src/main/java/com/example/lms/domain/user/entity/User.java
  lms/src/test/java/com/example/lms/domain/instructor/service/InstructorServiceTest.java
Labels: feature

#44 merge: develop <- feature/teaching-domain #40
  lms/src/main/java/com/example/lms/common/config/SecurityConfig.java
  lms/src/main/java/com/example/lms/domain/teaching/controller/TeachingController.java
  lms/src/main/java/com/example/lms/domain/teaching/controller/TeachingControllerDocs.java
  lms/src/main/java/com/example/lms/domain/teaching/dto/TeachingResponseDto.java
  lms/src/main/java/com/example/lms/domain/teaching/repository/TeachingRepository.java
  lms/src/main/java/com/example/lms/domain/teaching/service/TeachingService.java
  lms/src/test/java/com/example/lms/domain/teaching/service/TeachingServiceTest.java
Labels: feature

#46 merge: develop <- feature/ci-aws-setting
  .github/workflows/deploy-ec2.yml
  lms/Dockerfile
Labels: docs

#48 merge: develop <- feature/registration-domain #45
  lms/src/main/java/com/example/lms/common/config/SecurityConfig.java
  lms/src/main/java/com/example/lms/domain/instructor/entity/Instructor.java
  lms/src/main/java/com/example/lms/domain/registration/controller/RegistrationController.java
  lms/src/main/java/com/example/lms/domain/registration/controller/RegistrationControllerDocs.java
  lms/src/main/java/com/example/lms/domain/registration/dto/RegistrationCourseResponseDto.java
  lms/src/main/java/com/example/lms/domain/registration/dto/RegistrationStudentResponseDto.java
  lms/src/main/java/com/example/lms/domain/registration/entity/Registration.java
  lms/src/main/java/com/example/lms/domain/registration/repository/RegistrationRepository.java
  lms/src/main/java/com/example/lms/domain/registration/serveice/RegistrationService.java
  lms/src/main/java/com/example/lms/domain/teaching/dto/TeachingResponseDto.java
  lms/src/main/java/com/example/lms/domain/teaching/repository/TeachingRepository.java
  lms/src/main/java/com/example/lms/domain/teaching/service/TeachingService.java
  lms/src/test/java/com/example/lms/domain/registration/serveice/RegistrationServiceTest.java
Labels: feature

#50 merge: develop <- feature/student-domain #49
  lms/src/main/java/com/example/lms/common/config/SecurityConfig.java
  lms/src/main/java/com/example/lms/domain/instructor/controller/InstructorControllerDocs.java
  lms/src/main/java/com/example/lms/domain/registration/controller/RegistrationControllerDocs.java
  lms/src/main/java/com/example/lms/domain/student/controller/StudentController.java
  lms/src/main/java/com/example/lms/domain/student/controller/StudentControllerDocs.java
  lms/src/main/java/com/example/lms/domain/student/dto/StudentBasicInfoResponseDto.java
  lms/src/main/java/com/example/lms/domain/student/dto/StudentPersonalInfoResponseDto.java
  lms/src/main/java/com/example/lms/domain/student/dto/StudentUpdateRequestDto.java
  lms/src/main/java/com/example/lms/domain/student/entity/Student.java
  lms/src/main/java/com/example/lms/domain/student/service/StudentService.java
  lms/src/main/java/com/example/lms/domain/teaching/controller/TeachingControllerDocs.java
  lms/src/main/java/com/example/lms/domain/user/controller/UserControllerDocs.java
  lms/src/test/java/com/example/lms/domain/student/service/StudentServiceTest.java
Labels: feature

#51 feat: assignment 테스트 코드 작성 #7
  lms/src/main/java/com/example/lms/domain/assignment/controller/AssignmentGradeController.java
  lms/src/main/java/com/example/lms/domain/assignment/dto/SubmissionResponse.java
  lms/src/test/java/com/example/lms/domain/assignment/service/AssignmentGradeServiceTest.java
  lms/src/test/java/com/example/lms/domain/assignment/service/AssignmentServiceTest.java
  lms/src/test/java/com/example/lms/domain/assignment/service/SubmissionServiceTest.java
Labels: feature

#52 merge: develop <- feature/auth-security #5
  lms/src/main/java/com/example/lms/domain/user/controller/UserController.java
  lms/src/main/java/com/example/lms/domain/user/controller/UserControllerDocs.java
  lms/src/main/resources/application.yml
  lms/src/test/java/com/example/lms/domain/user/controller/UserControllerTest.java
Labels: feature
